// generated by shims/fill/gen.py — do not edit

@interface NSObject { void *isa; } @end

@interface CHHapticDynamicParameter : NSObject @end @implementation CHHapticDynamicParameter @end
@interface CHHapticEvent : NSObject @end @implementation CHHapticEvent @end
@interface CHHapticEventParameter : NSObject @end @implementation CHHapticEventParameter @end
@interface CHHapticPattern : NSObject @end @implementation CHHapticPattern @end
@interface DCDevice : NSObject @end @implementation DCDevice @end
@interface GCColor : NSObject @end @implementation GCColor @end
@interface GCDualSenseGamepad : NSObject @end @implementation GCDualSenseGamepad @end
@interface GCDualShockGamepad : NSObject @end @implementation GCDualShockGamepad @end
@interface GCXboxGamepad : NSObject @end @implementation GCXboxGamepad @end
@interface MTLCaptureDescriptor : NSObject @end @implementation MTLCaptureDescriptor @end
@interface NSBackgroundActivityScheduler : NSObject @end @implementation NSBackgroundActivityScheduler @end
@interface SMAppService : NSObject @end @implementation SMAppService @end

long AudioConverterNewSpecific(void) { return 0; }
long CAFrameRateRangeMake(void) { return 0; }
long CGColorGetTypeID(void) { return 0; }
long CGEventSourceKeyState(void) { return 0; }
long CVBufferRetain(void) { return 0; }
long CVImageBufferGetEncodedSize(void) { return 0; }
long CVMetalTextureCacheCreate(void) { return 0; }
long CVMetalTextureCacheCreateTextureFromImage(void) { return 0; }
long CVMetalTextureGetTexture(void) { return 0; }
long CVPixelBufferCreate(void) { return 0; }
long CVPixelBufferGetBytesPerRow(void) { return 0; }
long CVPixelBufferGetHeightOfPlane(void) { return 0; }
long CVPixelBufferGetPixelFormatType(void) { return 0; }
long CVPixelBufferGetWidthOfPlane(void) { return 0; }
long CVPixelBufferPoolCreatePixelBuffer(void) { return 0; }
long CVPixelBufferRelease(void) { return 0; }
long FSEventStreamCreate(void) { return 0; }
long FSEventStreamFlushSync(void) { return 0; }
long FSEventStreamInvalidate(void) { return 0; }
long FSEventStreamRelease(void) { return 0; }
long FSEventStreamSetDispatchQueue(void) { return 0; }
long FSEventStreamStart(void) { return 0; }
long FSEventStreamStop(void) { return 0; }
long KBGetLayoutType(void) { return 0; }
long LMGetKbdLast(void) { return 0; }
long LMGetKbdType(void) { return 0; }
long SCNetworkInterfaceGetInterfaceType(void) { return 0; }
long SCNetworkServiceCopy(void) { return 0; }
long SCNetworkServiceGetInterface(void) { return 0; }
long UTTypeConformsTo(void) { return 0; }
long UTTypeCreatePreferredIdentifierForTag(void) { return 0; }
long VTRegisterSupplementalVideoDecoderIfAvailable(void) { return 0; }

id CHHapticDynamicParameterIDHapticIntensityControl = @"CHHapticDynamicParameterIDHapticIntensityControl";
id CHHapticEventParameterIDHapticIntensity = @"CHHapticEventParameterIDHapticIntensity";
id CHHapticEventTypeHapticContinuous = @"CHHapticEventTypeHapticContinuous";
id GCControllerDidConnectNotification = @"GCControllerDidConnectNotification";
id GCControllerDidDisconnectNotification = @"GCControllerDidDisconnectNotification";
id GCHapticDurationInfinite = @"GCHapticDurationInfinite";
id GCHapticsLocalityHandles = @"GCHapticsLocalityHandles";
id GCHapticsLocalityLeftHandle = @"GCHapticsLocalityLeftHandle";
id GCHapticsLocalityLeftTrigger = @"GCHapticsLocalityLeftTrigger";
id GCHapticsLocalityRightHandle = @"GCHapticsLocalityRightHandle";
id GCHapticsLocalityRightTrigger = @"GCHapticsLocalityRightTrigger";
id GCHapticsLocalityTriggers = @"GCHapticsLocalityTriggers";
id GCInputButtonA = @"GCInputButtonA";
id GCInputButtonB = @"GCInputButtonB";
id GCInputButtonMenu = @"GCInputButtonMenu";
id GCInputButtonOptions = @"GCInputButtonOptions";
id GCInputButtonX = @"GCInputButtonX";
id GCInputButtonY = @"GCInputButtonY";
id GCInputDirectionPad = @"GCInputDirectionPad";
id GCInputDualShockTouchpadButton = @"GCInputDualShockTouchpadButton";
id GCInputDualShockTouchpadOne = @"GCInputDualShockTouchpadOne";
id GCInputDualShockTouchpadTwo = @"GCInputDualShockTouchpadTwo";
id GCInputLeftShoulder = @"GCInputLeftShoulder";
id GCInputLeftThumbstick = @"GCInputLeftThumbstick";
id GCInputLeftThumbstickButton = @"GCInputLeftThumbstickButton";
id GCInputLeftTrigger = @"GCInputLeftTrigger";
id GCInputRightShoulder = @"GCInputRightShoulder";
id GCInputRightThumbstick = @"GCInputRightThumbstick";
id GCInputRightThumbstickButton = @"GCInputRightThumbstickButton";
id GCInputRightTrigger = @"GCInputRightTrigger";
id GCInputXboxPaddleFour = @"GCInputXboxPaddleFour";
id GCInputXboxPaddleOne = @"GCInputXboxPaddleOne";
id GCInputXboxPaddleThree = @"GCInputXboxPaddleThree";
id GCInputXboxPaddleTwo = @"GCInputXboxPaddleTwo";
id NSProcessInfoPowerStateDidChangeNotification = @"NSProcessInfoPowerStateDidChangeNotification";
id NSProcessInfoThermalStateDidChangeNotification = @"NSProcessInfoThermalStateDidChangeNotification";
id kCVPixelBufferCGBitmapContextCompatibilityKey = @"kCVPixelBufferCGBitmapContextCompatibilityKey";
id kCVPixelBufferCGImageCompatibilityKey = @"kCVPixelBufferCGImageCompatibilityKey";
id kSCNetworkInterfaceTypeEthernet = @"kSCNetworkInterfaceTypeEthernet";
id kSCNetworkInterfaceTypeIEEE80211 = @"kSCNetworkInterfaceTypeIEEE80211";
id kTISNotifySelectedKeyboardInputSourceChanged = @"kTISNotifySelectedKeyboardInputSourceChanged";
id kTISPropertyInputSourceLanguages = @"kTISPropertyInputSourceLanguages";
id kTISPropertyUnicodeKeyLayoutData = @"kTISPropertyUnicodeKeyLayoutData";
id kUTTagClassFilenameExtension = @"kUTTagClassFilenameExtension";
id kUTTypeImage = @"kUTTypeImage";
id kUTTypeMovie = @"kUTTypeMovie";
id kVTDecompressionPropertyKey_RealTime = @"kVTDecompressionPropertyKey_RealTime";
id kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder = @"kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder";
id kVTVideoEncoderList_CodecType = @"kVTVideoEncoderList_CodecType";
id kVTVideoEncoderList_EncoderName = @"kVTVideoEncoderList_EncoderName";
id kVTVideoEncoderList_IsHardwareAccelerated = @"kVTVideoEncoderList_IsHardwareAccelerated";
