#!/usr/bin/env python3
"""Generate one fill dylib for every symbol the Roblox binaries import that Darling doesn't define.

Both RobloxPlayer *and* RobloxCrashHandler are scanned: the handler is posix_spawn'd by the player,
inherits DYLD_INSERT_LIBRARIES, and has imports of its own (SystemConfiguration interface-type
constants, among others). Missing one of them aborts the handler at load, and the player then
throws "Failed to initialize crash reporter" and exits.

683 of the 1614 imports are missing. Iterating them one crash at a time is not a plan, and dyld
binds most of them eagerly at load anyway, so they are all fatal at startup regardless of use.

Classification, from the Mach-O indirect symbol table:
  (__TEXT,__stubs) / __la_symbol_ptr  -> called as a function  -> empty function returning 0
  _OBJC_CLASS_$_Foo                   -> messaged             -> a real (empty) ObjC class
  everything else                     -> read as data         -> a constant NSString of its own name

Data constants must NOT be NULL. Almost all of them are CFStringRef/NSString constants used as
notification names and dictionary keys, and CoreFoundation dereferences them without checking:
a NULL kNSProcessInfoPowerStateDidChangeNotification segfaults inside CFNotificationCenterAddObserver
before the client ever opens its log. A unique string is inert wherever it lands.

ponytail: a function whose *address* is taken lands in __got, gets classified as data, and calls
through the string jump into nonsense. That is a loud, greppable crash; fix those by name here.
The few data constants that are not strings (GCHapticDurationInfinite is an NSTimeInterval) get a
pointer where a double belongs — harmless for the features we stub out.
"""
import pathlib, re, subprocess, sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent                       # runtime/
APP = pathlib.Path(__import__("os").environ.get("ROBLOX_MAC_APP", ROOT.parent / "RobloxPlayer.app"))
BINS = [APP / "Contents/MacOS/RobloxPlayer", APP / "Contents/MacOS/RobloxCrashHandler"]
DARLING = pathlib.Path(__import__("os").environ.get("DARLING_ROOT", ROOT / "darling-root"))


def defined_by_hand():
    """Symbols our own shims implement properly. The generated stub must not shadow them: under
    DYLD_FORCE_FLAT_NAMESPACE the first inserted library wins, and fill is inserted first."""
    libs = [p for p in HERE.parent.glob("*/*.dylib") if p.parent.name != "fill"]
    if not libs:
        return set()
    out = subprocess.run(["llvm-nm", "--defined-only", "--extern-only", "-j", *map(str, libs)],
                         capture_output=True, text=True).stdout
    return {l.strip() for l in out.splitlines() if l.strip() and not l.strip().endswith(":")}


def defined_by_darling():
    """Everything already available at runtime — Darling's root *and* the app's own dylibs."""
    # every dylib in the vendored root, not just the top-level ones: libSystem re-exports
    # ~30 libraries out of usr/lib/system/, and that is where the whole libc surface lives.
    libs = [p for p in list(DARLING.glob("System/Library/Frameworks/*.framework/Versions/*/*"))
            + list(DARLING.rglob("*.dylib"))
            + list(BINS[0].parent.glob("*.dylib"))  # @rpath libs shipped inside the app bundle
            if p.is_file() and not p.is_symlink()]
    out = subprocess.run(["llvm-nm", "--defined-only", "--extern-only", "-j", *map(str, libs)],
                         capture_output=True, text=True).stdout
    return {l.strip() for l in out.splitlines() if l.strip() and not l.strip().endswith(":")}


def imported():
    """undefined symbols of every Roblox binary -> True if called as a function"""
    syms = {}
    for binary in BINS:
        out = subprocess.run(["llvm-nm", "--undefined-only", "-j", str(binary)],
                             capture_output=True, text=True).stdout
        for l in out.splitlines():
            if l.strip():
                syms.setdefault(l.strip(), False)
        section, ind = None, subprocess.run(["llvm-otool", "-Iv", str(binary)],
                                            capture_output=True, text=True).stdout
        for line in ind.splitlines():
            m = re.match(r"Indirect symbols for \((\S+),(\S+)\)", line)
            if m:
                section = m.group(2)
                continue
            m = re.match(r"0x[0-9a-f]+\s+\S+\s+(\S+)", line)
            if m and section in ("__stubs", "__la_symbol_ptr") and m.group(1) in syms:
                syms[m.group(1)] = True    # called from any binary -> emit a function
    return syms


def emit(missing_funcs, missing_data, missing_classes, out):
    src = ["// generated by shims/fill/gen.py — do not edit\n"]
    src.append("@interface NSObject { void *isa; } @end\n")
    for c in sorted(missing_classes):
        src.append(f"@interface {c} : NSObject @end @implementation {c} @end")
    src.append("")
    for f in sorted(missing_funcs):
        src.append(f"long {f}(void) {{ return 0; }}")     # leading _ is added by the compiler
    src.append("")
    for d in sorted(missing_data):
        src.append(f'id {d} = @"{d}";')
    out.write_text("\n".join(src) + "\n")


def main():
    have, imports = defined_by_darling() | defined_by_hand(), imported()
    missing = {s: is_fn for s, is_fn in imports.items() if s not in have}
    classes, funcs, data = set(), set(), set()
    for s, is_fn in missing.items():
        bare = s[1:] if s.startswith("_") else s
        if bare.startswith("OBJC_CLASS_$_"):
            classes.add(bare[len("OBJC_CLASS_$_"):])
        elif is_fn:
            funcs.add(bare)
        else:
            data.add(bare)
    emit(funcs, data, classes, HERE / "fill.m")
    print(f"missing {len(missing)}: {len(funcs)} functions, {len(data)} data, {len(classes)} classes")
    (ROOT / "logs/missing-symbols.txt").write_text(
        "\n".join(f"{'FUNC' if v else 'DATA'} {k}" for k, v in sorted(missing.items())) + "\n")


if __name__ == "__main__":
    main()
