#version 450
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
layout(local_size_x_id=0,local_size_y_id=1,local_size_z_id=2) in;
layout(set=0,binding=0,std430) readonly buffer Params { uvec3 offset; uvec3 size; uvec2 stride; } params;
layout(set=0,binding=1,std430) readonly buffer Bytes { uint8_t data[]; } inputData;
layout(push_constant) uniform Dispatch { uint word[12]; } dispatchData;
#if CHANNELS==1
layout(set=0,binding=480,r8) uniform writeonly image2D outputImage;
#elif CHANNELS==2
layout(set=0,binding=480,rg8) uniform writeonly image3D outputImage;
#else
layout(set=0,binding=480,rgba8) uniform writeonly image3D outputImage;
#endif
void main() {
    uvec3 gid=gl_GlobalInvocationID+uvec3(dispatchData.word[3],dispatchData.word[4],dispatchData.word[5]);
    if (any(greaterThanEqual(gid,params.size))) return;
    uint index=gid.x+gid.y*params.stride.x;
#if CHANNELS!=1
    index+=gid.z*params.stride.y;
#endif
    vec4 value=vec4(0.0);
    for(uint c=0;c<CHANNELS;c++) value[c]=float(uint(inputData.data[index*CHANNELS+c]))/255.0;
#if CHANNELS==1
    imageStore(outputImage,ivec2(gid.xy+params.offset.xy),value);
#else
    imageStore(outputImage,ivec3(gid+params.offset),value);
#endif
}
